packages:
  - packages/*
  - examples/*
  - scripts

catalog:
  '@types/node': ^24.10.10
  ai: ^6.0.69
  tsx: ^4.20.6
  typescript: ^5.9.3

onlyBuiltDependencies:
  - esbuild
  - msw

shellEmulator: true
