packages:
  - packages/*
  - examples/*
  - scripts

catalog:
  '@types/node': ^24.10.8
  tsx: ^4.20.6
  typescript: ^5.9.3
  ai: ^6.0.62

onlyBuiltDependencies:
  - esbuild
  - msw

shellEmulator: true
